import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchAllReports, deleteReport } from '../../store/slices/reportSlice';
import { fetchProjects } from '../../store/slices/projectSlice';
import { fetchUsers } from '../../store/slices/userSlice';
import { Link } from 'react-router-dom';
import { FileText, Trash2, Calendar, User } from 'lucide-react';
import { toast } from 'react-hot-toast';

const ReportsListPage = () => {
    const dispatch = useDispatch();
    const { items: reports, loading } = useSelector((state) => state.reports);
    const { items: projects } = useSelector((state) => state.projects);
    const { items: users } = useSelector((state) => state.users);

    useEffect(() => {
        dispatch(fetchAllReports());
        dispatch(fetchProjects());
        dispatch(fetchUsers());
    }, [dispatch]);

    const getProjectName = (id) => projects.find(p => String(p.id) === String(id))?.project_name || id || 'Unknown Project';
    const getUserName = (id) => users.find(u => String(u.id) === String(id))?.name || id || 'Unknown User';

    const handleDelete = async (id) => {
        if (window.confirm('Are you sure you want to delete this report?')) {
            try {
                await dispatch(deleteReport(id)).unwrap();
                toast.success('Report deleted');
            } catch (error) {
                toast.error('Failed to delete report');
            }
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <table className="w-full text-left text-sm text-gray-500">
                    <thead className="bg-gray-50 text-xs uppercase text-gray-700">
                        <tr>
                            <th className="px-6 py-3">Report ID</th>
                            <th className="px-6 py-3">Project</th>
                            <th className="px-6 py-3">Generated By</th>
                            <th className="px-6 py-3">Date</th>
                            <th className="px-6 py-3 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {loading ? (
                            <tr><td colSpan="5" className="px-6 py-8 text-center">Loading reports...</td></tr>
                        ) : reports.length === 0 ? (
                            <tr><td colSpan="5" className="px-6 py-8 text-center">No reports found.</td></tr>
                        ) : (
                            reports.map((report) => (
                                <tr key={report.id} className="hover:bg-gray-50">
                                    <td className="px-6 py-4 font-medium text-gray-900 flex items-center gap-2">
                                        <FileText className="w-4 h-4 text-blue-500" />
                                        #{report.id.slice(0, 8)}
                                    </td>
                                    <td className="px-6 py-4 font-medium">{getProjectName(report.projectid)}</td>
                                    <td className="px-6 py-4">{getUserName(report.generated_by)}</td>
                                    <td className="px-6 py-4">{new Date(report.created_at).toLocaleDateString()}</td>
                                    <td className="px-6 py-4 text-right space-x-3">
                                        <Link to={`/reports/${report.id}`} className="text-blue-600 hover:text-blue-800 font-medium">View</Link>
                                        <button onClick={() => handleDelete(report.id)} className="text-red-600 hover:text-red-800"><Trash2 className="w-4 h-4" /></button>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default ReportsListPage;
