import React, { useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';
import PDFViewer from '../../components/shared/PDFViewer';
import { ArrowLeft, Clock, User as UserIcon, Calendar } from 'lucide-react';

const ReportViewerPage = () => {
    const { id } = useParams();
    const { items: reports } = useSelector((state) => state.reports);
    const report = reports.find((r) => r.id === id);

    if (!report) {
        return (
            <div className="flex flex-col items-center justify-center py-20">
                <p className="text-gray-500">Report not found.</p>
                <Link to="/projects" className="mt-4 text-blue-600 hover:underline">Return to Projects</Link>
            </div>
        );
    }

    return (
        <div className="h-full flex flex-col space-y-6">
            <div className="flex items-center justify-between">
                <div className="flex items-center space-x-4">
                    <Link to={`/projects/${report.projectid}`} className="p-2 hover:bg-gray-100 rounded-full transition-colors">
                        <ArrowLeft className="w-5 h-5 text-gray-600" />
                    </Link>
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900">Report Details</h1>
                        <p className="text-sm text-gray-500">Project Impact Assessment</p>
                    </div>
                </div>
            </div>

            <div className="flex-1 grid grid-cols-1 lg:grid-cols-4 gap-6 min-h-0">
                <div className="lg:col-span-3 h-full">
                    <PDFViewer
                        secureUrl={report.fileUrl}
                        signedUrl={report.signedUrl}
                        fileName={`Report_${id.slice(-6)}.pdf`}
                    />
                </div>

                <div className="space-y-6">
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
                        <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4">Metadata</h3>
                        <div className="space-y-4">
                            <div className="flex items-start space-x-3">
                                <Clock className="w-4 h-4 text-gray-400 mt-0.5" />
                                <div>
                                    <p className="text-xs text-gray-400 font-medium">Generated On</p>
                                    <p className="text-sm text-gray-700">{new Date(report.created_at).toLocaleString()}</p>
                                </div>
                            </div>
                            <div className="flex items-start space-x-3">
                                <UserIcon className="w-4 h-4 text-gray-400 mt-0.5" />
                                <div>
                                    <p className="text-xs text-gray-400 font-medium">Generated By</p>
                                    <p className="text-sm text-gray-700">{report.generated_by}</p>
                                </div>
                            </div>
                            <div className="flex items-start space-x-3">
                                <Calendar className="w-4 h-4 text-gray-400 mt-0.5" />
                                <div>
                                    <p className="text-xs text-gray-400 font-medium">Project ID</p>
                                    <p className="text-sm text-gray-700 font-mono text-xs">{report.projectid}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div className="bg-blue-50 p-6 rounded-xl border border-blue-100">
                        <h3 className="text-sm font-bold text-blue-900 uppercase tracking-wider mb-2">Summary</h3>
                        <p className="text-sm text-blue-800 leading-relaxed">
                            {report.summary}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReportViewerPage;
